### ISSUE TITLE
web: page titles all say "About RustSec"

### ISSUE THREAD

**Issue by tarcieri** [RustSec/rustsec-admin#131]
Small issue with the new web site generator introduced in #115: we lost page titles and they say "About RustSec"

It'd be good for `<title>` on the advisory pages to include the vulnerability ID and title

cc @ammaraskar

**Comment by ammaraskar** [comment]
Oh whoops, not sure how I forgot this. All that's needed is here:

https://github.com/RustSec/rustsec-admin/blob/e8ca8d98f794bf5d03c6316c9ed791c38fc6fe21/src/web/templates/advisory.html#L3

We need to add `{{ advisory.id() }}` etc, would you like to give this a shot to get familiar with the templating?

**Comment by tarcieri** [comment]
Yeah sure, I can take a look
